/** Shared service content — used by MongoDB seed and frontend fallback */
export const services = [
  {
    title: 'Front-End Development',
    slug: 'front-end-development',
    category: 'website-development',
    shortDescription: 'Create Stunning, Fast & User-Friendly Websites',
    description:
      'At A2S Ecom Solutions, we build modern, responsive, and visually appealing websites that deliver exceptional user experiences across all devices. Our Front-End Development services focus on creating engaging digital experiences that help businesses attract, engage, and convert customers.\n\nOur Development Process: (1) Requirement Analysis — understanding your business goals and project requirements. (2) Design & Planning — wireframes, layouts, and user-focused designs. (3) Development — responsive and interactive front-end interfaces. (4) Testing & Launch — quality, performance, and compatibility before deployment.\n\nLet\'s build something amazing — modern design, better experience, higher conversions.',
    icon: 'Monitor',
    features: [
      'Responsive website design',
      'Corporate & business websites',
      'Landing pages & portfolio websites',
      'E-commerce front-end interfaces',
      'Shopping cart & checkout page design',
      'UI/UX development & optimization',
      'HTML5, CSS3, JavaScript, Bootstrap, React.js, Tailwind CSS',
      'Speed & image optimization',
      'SEO-friendly structure & Core Web Vitals',
      'Modern & professional designs',
      'Mobile-first development',
      'Dedicated technical support',
      'Industries: E-Commerce, Retail, Finance, Healthcare, Education, Real Estate, Startups',
    ],
    order: 1,
    isFeatured: true,
  },
  {
    title: 'Back-End Development',
    slug: 'back-end-development',
    category: 'website-development',
    shortDescription: 'Powering Your Website with Secure & Scalable Solutions',
    description:
      'At A2S Ecom Solutions, we provide robust Back-End Development services that ensure your website or application runs smoothly, securely, and efficiently. Our back-end solutions handle business operations, manage data, and support seamless user experiences.\n\nOur Development Process: (1) Requirement Analysis. (2) System Architecture Planning. (3) Development & Integration. (4) Testing & Deployment. (5) Maintenance & Support.\n\nSecure systems. Powerful performance. Scalable growth.',
    icon: 'Server',
    features: [
      'Custom back-end & enterprise applications',
      'Database design, optimization & backup solutions',
      'Custom API development & third-party integrations',
      'Payment gateway, CRM & ERP integration',
      'E-commerce order & inventory management systems',
      'Server setup, cloud deployment & hosting management',
      'Data protection & user authentication systems',
      'PHP, Laravel, Node.js, Python, MySQL, PostgreSQL, MongoDB',
      'Secure & scalable architecture',
      'Ongoing technical support',
      'Industries: E-Commerce, Retail, Finance, Healthcare, Education, Logistics',
    ],
    order: 2,
    isFeatured: true,
  },
  {
    title: 'CMS Development',
    slug: 'cms-development',
    category: 'website-development',
    shortDescription: 'Custom content management systems for easy updates.',
    description:
      'Streamline your content strategy with customized CMS solutions. Easily update, manage, and publish dynamic content.',
    icon: 'FileText',
    features: ['Easy content editing', 'Role-based access', 'Media management', 'SEO-friendly'],
    order: 3,
  },
  {
    title: 'Web App Development',
    slug: 'web-app-development',
    category: 'website-development',
    shortDescription: 'Custom web applications tailored to your business.',
    description:
      'We create custom websites from your vision. Scalable, easy-to-use web app solutions designed for your business needs.',
    icon: 'AppWindow',
    features: ['Custom solutions', 'Scalable apps', 'User-friendly', 'Cloud-ready'],
    order: 4,
    isFeatured: true,
  },
  {
    title: 'UI/UX Web Designing',
    slug: 'ui-ux-web-designing',
    category: 'website-development',
    shortDescription: 'Visually appealing, user-focused designs that convert.',
    description:
      'Improved usability through visually appealing and user-focused designs that enhance engagement and conversion rates.',
    icon: 'Palette',
    features: ['Wireframing', 'Prototyping', 'User research', 'Design systems'],
    order: 5,
  },
  {
    title: 'API Development',
    slug: 'api-development',
    category: 'website-development',
    shortDescription: 'Versatile APIs to connect systems and expand capabilities.',
    description:
      'Combine various systems with API development designed to improve capabilities, interface with services, and ensure versatility.',
    icon: 'Plug',
    features: ['REST & GraphQL', 'Third-party integration', 'Documentation', 'Secure endpoints'],
    order: 6,
  },
  {
    title: 'Search Engine Optimization',
    slug: 'search-engine-optimization',
    category: 'digital-marketing',
    shortDescription: 'Improve Your Rankings, Traffic & Online Visibility',
    description:
      'At A2S Ecom Solutions, we provide result-driven SEO services to help your website rank higher on search engines, attract quality traffic, and generate more leads and sales.\n\nOur SEO Process: (1) Research & Analysis. (2) Strategy Development. (3) Optimization & Implementation. (4) Monitoring & Reporting.\n\nRank higher. Drive more traffic. Grow faster.',
    icon: 'Search',
    features: [
      'Complete website SEO audit & technical review',
      'Keyword research, on-page & meta optimization',
      'Website speed & mobile-friendly optimization',
      'XML sitemap, robots.txt & schema markup',
      'High-quality backlink building & outreach',
      'Google Business Profile & local SEO',
      'E-commerce product & category page optimization',
      'White-hat SEO techniques',
      'Transparent monthly reporting',
      'Industries: E-Commerce, Retail, Healthcare, Education, Finance, Technology',
    ],
    order: 1,
    isFeatured: true,
  },
  {
    title: 'Social Media Marketing',
    slug: 'social-media-marketing',
    category: 'digital-marketing',
    shortDescription: 'Grow Your Brand, Engage Your Audience & Increase Sales',
    description:
      'At A2S Ecom Solutions, we provide result-driven Social Media Marketing (SMM) services to help businesses build brand awareness, engage customers, generate leads, and drive sales across major social media platforms.\n\nOur Process: (1) Business & Audience Analysis. (2) Content & Campaign Planning. (3) Execution & Management. (4) Monitoring & Optimization.\n\nCreate awareness. Build engagement. Drive sales.',
    icon: 'Share2',
    features: [
      'Social media strategy & competitor analysis',
      'Account setup, optimization & daily management',
      'Post designs, reels, stories & brand content',
      'Facebook, Instagram, LinkedIn & YouTube ads',
      'Lead generation & remarketing campaigns',
      'Brand awareness & reputation management',
      'Performance tracking & monthly reports',
      'Platforms: Facebook, Instagram, LinkedIn, YouTube, X, Pinterest, Threads',
      'Creative content strategies',
      'Industries: E-Commerce, Retail, Healthcare, Education, Finance, Real Estate',
    ],
    order: 2,
    isFeatured: true,
  },
  {
    title: 'Performance Marketing',
    slug: 'performance-marketing',
    category: 'digital-marketing',
    shortDescription: 'Data-driven campaigns for maximum ROI.',
    description:
      'Paid media campaigns optimized through data analytics for immediate and efficient conversion to monetary value.',
    icon: 'TrendingUp',
    features: ['PPC campaigns', 'Conversion tracking', 'A/B testing', 'ROI optimization'],
    order: 3,
  },
  {
    title: 'Content Marketing',
    slug: 'content-marketing',
    category: 'digital-marketing',
    shortDescription: 'High-quality blogs, videos, and eBooks aligned with your brand.',
    description:
      'Our writers and SEO specialists develop unique content that strengthens your position and expands your readership.',
    icon: 'PenTool',
    features: ['Blog writing', 'Video content', 'eBooks', 'Content strategy'],
    order: 4,
  },
  {
    title: 'Logo Design',
    slug: 'logo-design',
    category: 'graphic-branding',
    shortDescription: 'Build a Strong Brand Identity with Professional Logo Design',
    description:
      'At A2S Ecom Solutions, we create unique, memorable, and impactful logos that represent your brand\'s vision, values, and professionalism. A well-designed logo is the foundation of a strong brand identity.\n\nOur Design Process: (1) Brand Discovery. (2) Concept Creation. (3) Design Refinement. (4) Final Delivery with print & digital-ready files.\n\nCreative designs. Strong branding. Lasting impressions.',
    icon: 'Sparkles',
    features: [
      'Unique & original custom logo concepts',
      'Wordmark, lettermark, icon & combination logos',
      'Brand color selection & typography recommendations',
      'Logo redesign & brand refresh',
      'High-resolution PNG, JPEG & vector files (AI, EPS, SVG)',
      'Transparent background & social media formats',
      'Multiple design concepts',
      'Fast turnaround time',
      'Industries: E-Commerce, Retail, Technology, Finance, Healthcare, Startups',
    ],
    order: 1,
    isFeatured: true,
  },
  {
    title: 'Corporate Branding',
    slug: 'corporate-branding',
    category: 'graphic-branding',
    shortDescription: 'Build a Powerful Brand That Inspires Trust & Growth',
    description:
      'At A2S Ecom Solutions, we help businesses create a strong and professional brand identity that stands out in the market. Our Corporate Branding services establish credibility, increase brand recognition, and create a lasting impression.\n\nOur Branding Process: (1) Brand Discovery. (2) Strategy Development. (3) Design & Identity Creation. (4) Brand Implementation. (5) Ongoing Brand Support.\n\nBuild trust. Create impact. Grow your brand.',
    icon: 'Building2',
    features: [
      'Brand strategy, positioning & personality development',
      'Professional logo & visual identity design',
      'Business cards, letterheads & email signatures',
      'Brochures, flyers, catalogs & presentations',
      'Website & social media branding',
      'Brand usage guidelines & style guides',
      'Consistent brand identity across all platforms',
      'Industries: E-Commerce, Retail, Technology, Finance, Healthcare, Real Estate',
    ],
    order: 2,
  },
  {
    title: 'E-Commerce Account Management',
    slug: 'ecommerce-account-management',
    category: 'ecommerce-setup',
    shortDescription: 'Grow Your Online Business with Professional Account Management',
    description:
      'At A2S Ecom Solutions, we provide complete E-Commerce Account Management services to help sellers maximize sales, improve visibility, and grow their business across leading online marketplaces.\n\nOur Process: (1) Account Audit. (2) Strategy Planning. (3) Account Optimization. (4) Growth & Monitoring.\n\nGrow your sales. Expand your reach. Build your brand.',
    icon: 'Store',
    features: [
      'New seller account registration & GST assistance',
      'Product listing creation & SEO-optimized descriptions',
      'Inventory & stock monitoring',
      'Order processing, returns & customer communication',
      'Amazon, Flipkart, Meesho, JioMart, Myntra, Ajio management',
      'Account health & Buy Box optimization',
      'Amazon PPC & sponsored ads campaigns',
      'Sales performance reports & growth recommendations',
      'Dedicated account manager',
      'Multi-marketplace expertise',
      'Platforms: Amazon, Flipkart, Meesho, JioMart, Myntra, Ajio, Snapdeal',
    ],
    order: 1,
    isFeatured: true,
  },
  {
    title: 'E-Commerce SEO',
    slug: 'ecommerce-seo',
    category: 'ecommerce-setup',
    shortDescription: 'Boost Your Product Visibility & Drive More Sales',
    description:
      'At A2S Ecom Solutions, we specialize in E-Commerce SEO services that help online stores rank higher, attract qualified customers, and increase sales across websites and marketplaces.\n\nOur SEO Process: (1) Website & Store Audit. (2) SEO Strategy Development. (3) Optimization & Implementation. (4) Monitoring & Continuous Improvement.\n\nRank higher. Sell more. Grow faster.',
    icon: 'BarChart3',
    features: [
      'Product & competitor keyword research',
      'SEO-friendly product titles & descriptions',
      'Category page & technical SEO optimization',
      'Amazon, Flipkart & Meesho listing optimization',
      'Blog content, buying guides & link building',
      'Website speed & mobile responsiveness',
      'Platforms: Shopify, WooCommerce, Magento, Amazon, Flipkart, Meesho',
      'White-hat SEO & detailed performance reporting',
    ],
    order: 2,
  },
  {
    title: 'Brand Registry & Protection',
    slug: 'brand-registry-protection',
    category: 'ecommerce-setup',
    shortDescription: 'Protect your brand from copying and competition.',
    description:
      'From brand registry to category optimization, sponsored ads, order management, and feedback management.',
    icon: 'Shield',
    features: ['Brand registry', 'IP protection', 'Category optimization', 'Monitoring'],
    order: 3,
  },
  {
    title: 'Business Consulting',
    slug: 'business-consulting',
    category: 'business-growth',
    shortDescription: 'Transform Your Business with Expert Consulting',
    description:
      'At A2S Ecom Solutions, we help businesses improve performance, increase profitability, and achieve sustainable growth. Our expert consulting services identify opportunities, solve challenges, and create strategies that drive success.\n\nOur Process: (1) Business Assessment. (2) Strategy Development. (3) Implementation Support. (4) Performance Review.\n\nReady to take your business to the next level? Contact A2S Ecom Solutions today.',
    icon: 'Briefcase',
    features: [
      'Business growth planning & market analysis',
      'Competitive benchmarking & revenue strategies',
      'Process optimization & cost reduction',
      'Sales strategy & lead generation planning',
      'E-commerce & marketplace consulting',
      'Amazon, Flipkart, Meesho seller guidance',
      'Budget planning & profitability analysis',
      'HR & team productivity improvement',
      'Experienced business consultants',
      'Customized, data-driven strategies',
      'Industries: E-Commerce, Retail, Manufacturing, Finance, Healthcare, Education, Real Estate, Startups',
    ],
    order: 1,
    isFeatured: true,
  },
  {
    title: 'Sales Funnels',
    slug: 'sales-funnels',
    category: 'business-growth',
    shortDescription: 'Turn Visitors into Customers with High-Converting Sales Funnels',
    description:
      'At A2S Ecom Solutions, we design and optimize sales funnels that guide potential customers through every stage of the buying journey—from awareness to conversion.\n\nOur Process: (1) Business Analysis. (2) Funnel Design. (3) Development & Automation. (4) Testing & Optimization.\n\nAttract more leads. Convert more customers. Grow more revenue.',
    icon: 'Filter',
    features: [
      'Customer journey mapping & funnel architecture',
      'High-converting landing & sales pages',
      'Lead capture forms & lead magnets',
      'Product launch & upsell funnels',
      'Cart abandonment recovery',
      'Email marketing automation & welcome sequences',
      'Conversion rate optimization & A/B testing',
      'Industries: E-Commerce, Retail, Education, Real Estate, Healthcare, Finance',
    ],
    order: 2,
  },
  {
    title: 'Product Listing on Seller Central',
    slug: 'seller-central-listing',
    category: 'seller-central',
    shortDescription: 'Optimize Your Products for Maximum Visibility and Sales',
    description:
      'At A2S Ecom Solutions, we provide professional Product Listing Services for Seller Central platforms such as Amazon, Flipkart, Meesho, JioMart, Myntra, and other marketplaces. Our experts create and optimize listings that improve search rankings, attract customers, and increase conversions.\n\nOur Process: (1) Product Information Collection. (2) Listing Creation. (3) Quality Check. (4) Publishing & Monitoring.\n\nBetter listings. Better visibility. Better sales.',
    icon: 'Upload',
    features: [
      'New product listing & category selection',
      'SEO-friendly titles & keyword-rich bullet points',
      'Product image uploading & optimization',
      'Bulk listing uploads & variation setup',
      'A+ content & catalog error resolution',
      'Regular price & inventory synchronization',
      'Amazon, Flipkart, Meesho, JioMart, Myntra, Ajio support',
      'Marketplace listing experts',
      'Higher product visibility & conversion rates',
    ],
    order: 1,
    isFeatured: true,
  },
  {
    title: 'Price & Quantity Management',
    slug: 'price-quantity-management',
    category: 'seller-central',
    shortDescription: 'Optimize Inventory, Pricing & Profitability',
    description:
      'At A2S Ecom Solutions, we provide professional Price & Quantity Management services to help sellers maintain accurate inventory levels, competitive pricing, and smooth marketplace operations.\n\nOur Process: (1) Inventory Assessment. (2) Strategy Planning. (3) Implementation. (4) Monitoring & Optimization.\n\nSmart pricing. Accurate inventory. Higher sales.',
    icon: 'IndianRupee',
    features: [
      'Stock quantity updates & low-stock alerts',
      'Competitive pricing analysis & margin optimization',
      'Bulk inventory & price revisions',
      'Multi-channel inventory synchronization',
      'Amazon, Flipkart, Meesho, JioMart, Myntra management',
      'Demand forecasting & reorder recommendations',
      'Inventory error & sync issue resolution',
      'Reduced stock-out risks',
    ],
    order: 2,
  },
  {
    title: 'Negative Feedback Management',
    slug: 'negative-feedback-management',
    category: 'seller-central',
    shortDescription: 'Proactive removal of policy-violating negative feedback.',
    description:
      'Proactive work on removal of negative feedback not per marketplace policies. Notification management and POA when required.',
    icon: 'MessageSquareWarning',
    features: ['Policy review', 'POA submission', 'Notification handling', 'Rating protection'],
    order: 3,
  },
  {
    title: 'A-Z Claim Management',
    slug: 'az-claim-management',
    category: 'seller-central',
    shortDescription: 'Represent cases to close or fund A-Z claims.',
    description:
      'Service provider represents cases against A-Z claims filed by buyers to get them closed or funded by marketplace safe-t claims.',
    icon: 'Scale',
    features: ['Case representation', 'Documentation', 'Safe-t claims', 'Resolution tracking'],
    order: 4,
  },
  {
    title: 'FBA Shipment Creation',
    slug: 'fba-shipment-creation',
    category: 'seller-central',
    shortDescription: 'Shipment creation, CARP appointments, and tracking.',
    description:
      'Assist sellers in creation of shipments, taking CARP appointments and tracking shipments on behalf of the seller.',
    icon: 'Truck',
    features: ['Shipment setup', 'CARP appointments', 'Tracking', 'Label support'],
    order: 5,
  },
  {
    title: 'Sponsored Ads Management',
    slug: 'sponsored-ads-management',
    category: 'seller-central',
    shortDescription: 'Low ACOS campaigns with optimized daily budgets.',
    description:
      'Campaign creation, ad optimization keeping low ACOS and high sales, with bid amounts and daily budgets for targeted visibility.',
    icon: 'Megaphone',
    features: ['Campaign creation', 'ACOS optimization', 'Bid management', 'Performance reports'],
    order: 6,
    isFeatured: true,
  },
  {
    title: 'Buyer-Seller Communication',
    slug: 'buyer-seller-communication',
    category: 'seller-central',
    shortDescription: 'Respond to queries within 24 hours (up to 100 msgs/week).',
    description:
      'Respond to buyer and marketplace queries within 24 hrs per contact response policy to protect from negative ratings.',
    icon: 'MessagesSquare',
    features: ['24hr response', 'Up to 100 msgs/week', 'Template responses', 'Rating protection'],
    order: 7,
  },
];
